toml
[versions]
agp = "8.12.3"
desugar_jdk_libs = "2.1.5"
kotlin = "2.0.21"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.9.4"
activityCompose = "1.11.0"
composeBom = "2024.09.00"
roomKtxVersion = "2.6.1"
roomRuntime = "2.8.1"
ksp = "2.0.21-1.0.20" #  Add this line - match your Kotlin version

[libraries]
# ... other libraries
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomKtxVersion" } # Assuming you also want to manage this here

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
google-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" } # Add this line
    